language: c
env:
 global: 
   - ESP32TOOLS=/home/travis/.arduino15/packages/esp32/hardware/esp32/1.0.6/tools
   - MKSPIFFS=/home/travis/.arduino15/packages/esp32/tools/mkspiffs/0.2.3/mkspiffs
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget https://downloads.arduino.cc/arduino-1.8.13-linux64.tar.xz
  - tar xf arduino-1.8.13-linux64.tar.xz
  - sudo mv arduino-1.8.13 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
  - wget https://github.com/me-no-dev/ESPAsyncWebServer/archive/master.zip
  - unzip master.zip
  - rm master.zip
  - sudo mv ESPAsyncWebServer-master /usr/local/share/arduino/libraries/ESPAsyncWebServer
  - wget https://github.com/me-no-dev/AsyncTCP/archive/master.zip
  - unzip master.zip
  - rm master.zip
  - sudo mv AsyncTCP-master /usr/local/share/arduino/libraries/AsyncTCP
  - wget https://github.com/me-no-dev/arduino-esp32fs-plugin/releases/download/1.0/ESP32FS-1.0.zip
  - wget https://github.com/lewisxhe/AXP202X_Library/archive/refs/tags/V1.1.3.zip
  - unzip V1.1.3.zip
  - sudo mv AXP202X_Library-1.1.3 /usr/local/share/arduino/libraries/

  - wget https://github.com/dx168b/async-mqtt-client/archive/master.zip
  - unzip master.zip
  - rm master.zip
  - sudo mv async-mqtt-client-master /usr/local/share/arduino/libraries/

  # Trying to get rid of mDNS warnings (1000s of them...)
  # as suggested by https://forum.arduino.cc/index.php?topic=469428.0
  # Arduino IDE adds a lot of noise caused by network traffic, trying to firewall it off
  - sudo iptables -P INPUT DROP
  - sudo iptables -P FORWARD DROP
  - sudo iptables -P OUTPUT ACCEPT
  - sudo iptables -A INPUT -i lo -j ACCEPT
  - sudo iptables -A OUTPUT -o lo -j ACCEPT
  - sudo iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

install:
  - arduino --pref "boardsmanager.additional.urls=https://dl.espressif.com/dl/package_esp32_index.json" --save-prefs
  - arduino --pref "build.verbose=true" --save-prefs
  - arduino --pref "custom_FlashFreq=ttgo-lora32-v1_80" --save-prefs
  - mkdir -p $PWD/build
  - arduino --pref "build.path=$PWD/build" --save-prefs
  - arduino --install-boards esp32:esp32:1.0.6 --save-prefs
  - ln -s $PWD/libraries/SondeLib /usr/local/share/arduino/libraries/SondeLib
  - arduino --install-library "U8g2"
  - arduino --install-library "MicroNMEA"
  - arduino --install-library "GFX Library for Arduino"
script:
  - arduino --board esp32:esp32:t-beam --verify $PWD/RX_FSK/RX_FSK.ino
  - find build
  - find /home/travis/.arduino15/packages/esp32/hardware/esp32/
  - $PWD/scripts/makeimage.py $ESP32TOOLS $PWD/build/RX_FSK.ino.bin $PWD/RX_FSK/data $PWD/out.bin
after_success:
  - .travis/push.sh  
notifications:
  email:
    on_success: change
    on_failure: change
